language: generic 

services:
    - docker 

before_install:
    - docker build -t jubair007/jubair-docker -f Dockerfile.dev .

    script:
        - docker run -e CI=true jubair007/jubair-docker npm run test
