language: generic 
sudo : required
services :
    - docker

before_install:
    - docker run -t jubair 007/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jubair007/docker-react npm run test